apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/sriov-fec.openshift-operators: ""
  name: sriov-fec
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: sriov-fec
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: sriov-fec.v2.7.1
