
---
apiVersion: v1
kind: Secret
metadata:
  name: sno-secret-spoke01
  namespace: spoke01-cluster
data:
  username: cm9vdA==  #base64
  password: Q2FsdmluY2FsdmluMTIzCg==  #base64
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
  namespace:  spoke01-cluster
stringData:
  .dockerconfigjson: 'your pullsecret'