---
apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: performance
spec:
  # cpu:
  #   isolated: 4-7
  #   reserved: "0-3"
  machineConfigPoolSelector:
    pools.operator.machineconfiguration.openshift.io/master: ""
  net:
    userLevelNetworking: false
  nodeSelector:
    node-role.kubernetes.io/master: ""
  numa:
    topologyPolicy: best-effort
  realTimeKernel:
    enabled: false
  workloadHints:
    highPowerConsumption: true
    perPodPowerManagement: false
    realTime: true
