
---
apiVersion: v1
kind: Secret
metadata:
  name: sno-secret-spoke02
  namespace: spoke02-cluster
data:
  username: cm9vdA==
  password: Q2FsdmluY2FsdmluMTIzCg==
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
  namespace:  spoke02-cluster
stringData:
  .dockerconfigjson: 'your pullsecret'