# apiVersion: lvm.topolvm.io/v1alpha1
# kind: LVMCluster
# metadata:
#   name: lvms-operator
#   namespace: openshift-storage
# spec:
#   storage:
#     deviceClasses:
#     - name: vg1
#       thinPoolConfig:
#         name: thin-pool-1
#         sizePercent: 90
#         overprovisionRatio: 10
apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: lvms-operator
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
    - name: vg1
      deviceSelector:
          paths:
            - /dev/sdb
      thinPoolConfig:
        name: thin-pool-1
        sizePercent: 90
        overprovisionRatio: 10