apiVersion: v1
kind: Node
metadata:
  name: xr11-1-vdu
  labels:
    operators.coreos.com/sriov-fec.openshift-operators: ''
    feature.node.kubernetes.io/network-sriov.capable: 'true'
    tiger-storage: 'true'
